import { MissionId } from './types';

export interface AdventureStory {
  title: string;
  story: string;
  guide: string;
  whyItMatters: string;
  focus: string;
}

export const MISSION_INTROS: Record<MissionId, AdventureStory> = {
  1:{title:'Welcome to Adom and Nkabom',story:'Two lively communities sit on opposite sides of the river. Schoolchildren, farmers and traders make the long trip around it every day. Ama is waiting to show you what life is like before anyone talks about building.',guide:'Ama: “Look around carefully. A good project starts by understanding the people it is meant to help.”',whyItMatters:'Before using numbers, you need to know the problem the numbers are helping you solve.',focus:'Explore the community, listen to people and collect useful clues.'},
  2:{title:'Adventure to the Riverbank',story:'Kojo leads you down to the river. There are several places where a crossing might go, but each place has different advantages. You will investigate the land, measure the water crossing and look for signs of seasonal flooding.',guide:'Kojo: “Do not rush! The river has clues everywhere — on the banks, in old photos and in the stories people tell.”',whyItMatters:'Measurements and environmental clues will affect many calculations later in the adventure.',focus:'Compare sites, measure carefully and record what you discover.'},
  3:{title:'Three Bridge Ideas',story:'Your survey notebook is ready. Now the community wants you to compare three fictional Mezzo bridge systems: Timber, Steel and Reinforced Concrete. Each one has different simulation costs, transport needs and project features.',guide:'Ama: “There is no magic bridge that is always best. Use the clues from this adventure to make your choice.”',whyItMatters:'Real problem solving means comparing information, not memorising one answer.',focus:'Compare the three Design Cards and explain your choice.'},
  4:{title:'Turn Your Maths Into Materials',story:'The chosen bridge idea now needs materials. This is where your calculations become visible objects: modules, deck units, connection tokens, packages and other fictional resources.',guide:'Kojo: “Every number you enter changes what the project can buy. Too little may create a shortage; too much may waste money.”',whyItMatters:'This mission connects multiplication, division, area, percentages and rounding to practical quantities.',focus:'Calculate what is needed, then turn the quantities into whole packages.'},
  5:{title:'Can We Deliver It and Afford It?',story:'The materials have been planned, but they are still at the supplier. You must work out how many trips are needed, what those trips cost, what the work schedule costs and whether the whole project fits the community budget.',guide:'Ama: “A good plan is not only about buying things. We must get everything to the river and keep an eye on the money.”',whyItMatters:'Transport and budgeting show how arithmetic decisions affect the whole project.',focus:'Plan trucks, labour and the final money total.'},
  6:{title:'The Trucks Have Arrived!',story:'The construction site is busy. What appears at the river depends on the quantities you ordered and the trips you planned. Nothing is secretly corrected for you.',guide:'Kojo: “Check every delivery before we test anything. If something is missing, this is your chance to spot it.”',whyItMatters:'Your earlier mathematics now becomes visible in the construction world.',focus:'Inspect what arrived and decide whether the virtual bridge is ready for testing.'},
  7:{title:'The Big Test',story:'The bridge is built from the project decisions you made. Now the community watches as it goes through normal-use, busy-time and environmental tests. If a problem appears, you will investigate the symptom, find the cause and fix only what needs fixing.',guide:'Ama: “A problem is not the end of the adventure. Good mathematicians investigate, learn and improve their solution.”',whyItMatters:'Testing helps you see how measurements, quantities, logistics and environmental clues work together.',focus:'Test, diagnose, redesign if needed, then tell the story of your project.'},
};

export const MISSION_OUTROS: Record<MissionId, AdventureStory> = {
  1:{title:'Community Clues Collected!',story:'You now understand why the crossing matters and how much travel it could save. Your notebook is ready for the river investigation.',guide:'Ama: “Great start! Kojo is waiting at the riverbank with the measuring tools.”',whyItMatters:'You have connected community data to distance and percentage mathematics.',focus:'Next stop: the river.'},
  2:{title:'River Exploration Complete!',story:'You selected a crossing, measured the span, read the walkway brief, investigated flood clues and prepared a scale plan.',guide:'Kojo: “We have enough evidence to visit the design room.”',whyItMatters:'The numbers you recorded here will drive later quantities.',focus:'Next stop: choose your bridge idea.'},
  3:{title:'Bridge Idea Chosen!',story:'You compared the three fictional systems and recorded a reason for your choice. The materials team can now open the correct Mezzo Design Card.',guide:'Ama: “Your choice is made. Now let us turn that design into quantities.”',whyItMatters:'Reasoning has now become a plan that mathematics can work with.',focus:'Next stop: materials.'},
  4:{title:'Shopping List Ready!',story:'Your calculations have created a material order with whole packages and a cost. Those numbers will determine what the supplier prepares.',guide:'Kojo: “The order is ready, but the materials still need trucks to reach the river.”',whyItMatters:'Your arithmetic is about to affect real-looking deliveries in the simulation.',focus:'Next stop: deliveries and budget.'},
  5:{title:'Project Plan Ready!',story:'You have planned the trips, transport cost, labour cost and complete budget. The supplier can now load the trucks according to your decisions.',guide:'Ama: “Time to see whether our maths gets everything to the construction site.”',whyItMatters:'Logistics and money decisions will now have visible consequences.',focus:'Next stop: build and inspect.'},
  6:{title:'Inspection Complete!',story:'You have checked what arrived and made a decision about testing. If you approved the project, the community is ready for the big moment.',guide:'Kojo: “Everyone is gathering near the crossing. Let us test it carefully.”',whyItMatters:'Inspection gives you a chance to catch a problem before testing.',focus:'Next stop: test, fix and celebrate.'},
  7:{title:'Adventure Complete!',story:'Your final project story brings together the community problem, measurements, calculations, materials, money, testing and any redesign work you completed.',guide:'Ama and Kojo: “You did more than answer maths questions — you used maths to solve a community challenge!”',whyItMatters:'The final result shows both what happened to the project and what mathematical skills you demonstrated.',focus:'Review your project outcome and competency report.'},
};

export const DECISION_STORIES: Record<number, AdventureStory> = {
  1:{title:'What Is the Real Problem?',story:'Residents describe long journeys between the two communities. Read the choices and decide which problem this project is really trying to solve.',guide:'Ama: “Listen to what people are actually saying, not what you expect them to say.”',whyItMatters:'Correctly identifying a problem is the first step in solving it.',focus:'Data interpretation and problem solving.'},
  2:{title:'When Is the Crossing Busiest?',story:'Daily users and peak simultaneous users are different. The project team needs the number of people who may be using the crossing at the busiest moment.',guide:'Ama: “Look for the peak-use clue, not the total number for the whole day.”',whyItMatters:'Choosing the right data matters just as much as doing the calculation.',focus:'Read and interpret community-use data.'},
  3:{title:'How Much Distance Could We Save?',story:'The existing route is given in kilometres while the new route is shown in metres. Put them in the same unit before comparing them.',guide:'Ama: “Different units can trick you. Make them match first.”',whyItMatters:'Unit conversion lets you compare quantities fairly.',focus:'Convert units and subtract.'},
  4:{title:'How Big Is the Improvement?',story:'A distance saving is useful, but a percentage tells the community how large the improvement is compared with the original journey.',guide:'Ama: “Ask: what fraction of the old journey disappears?”',whyItMatters:'Percentages help people compare changes of different sizes.',focus:'Percentage reduction.'},
  5:{title:'Pick the Best Crossing Spot',story:'Three river locations have different access, environmental, convenience and cost clues. The shortest crossing is not automatically the best.',guide:'Kojo: “Balance all the clues. A good choice can have more than one reason.”',whyItMatters:'Optimisation means weighing several pieces of information together.',focus:'Compare evidence and justify a choice.'},
  6:{title:'Measure the River Yourself',story:'The correct span is hidden. Use the measurement tool and line up both riverbank markers as carefully as you can.',guide:'Kojo: “Careful measuring now can save a lot of trouble later.”',whyItMatters:'Your measured span will influence later calculations.',focus:'Measurement and estimation.'},
  7:{title:'Read the Community Brief',story:'The walkway width is already stated in the project brief. Your job is to carry the right value into your plan without changing it.',guide:'Kojo: “Sometimes mathematics starts with reading the instructions accurately.”',whyItMatters:'Using the wrong given value can create a later usability problem.',focus:'Read and transfer measurement data.'},
  8:{title:'Find the Flood Clue',story:'Residents, water marks and old images show that the river changes during the rainy season. Decide whether this information belongs in the project record.',guide:'Kojo: “A clue can seem unimportant now and become very important later.”',whyItMatters:'Environmental information must be available before it can fairly affect later testing.',focus:'Data interpretation and environmental reasoning.'},
  9:{title:'Make a Mini Scale Plan',story:'A scale drawing shrinks the crossing while keeping the same relationship. Use your own recorded span and the scale shown on the planning board.',guide:'Kojo: “Your drawing is smaller, but the mathematics must still represent the same crossing.”',whyItMatters:'Scale helps turn real-sized measurements into usable plans.',focus:'Ratio, scale and division.'},
  10:{title:'Choose Your Bridge Idea',story:'Compare the three fictional Mezzo Design Cards. Think about cost, transport, availability, time and environmental clues before explaining your choice.',guide:'Ama: “Any of the three can work. I want to hear why your choice fits this adventure.”',whyItMatters:'A strong solution is supported by evidence rather than guessing.',focus:'Planning, reasoning and optimisation.'},
  11:{title:'Read the Design Card',story:'Your chosen system has its own set of fictional project components. Identify the component family that belongs to the Design Card you selected.',guide:'Kojo: “Make sure you are reading the card for your bridge, not one of the other ideas.”',whyItMatters:'Good calculations begin with the correct information.',focus:'Interpret a technical-looking learning diagram.'},
  12:{title:'How Many Modules?',story:'A module covers part of the crossing. If the final division gives a fraction, the project still needs a complete final module.',guide:'Kojo: “A bridge cannot order 0.4 of an indivisible module.”',whyItMatters:'This is practical rounding: sometimes you must round up, not to the nearest number.',focus:'Division and upward rounding.'},
  13:{title:'Count the Main Pieces',story:'Each module needs a set number of primary member units. Use the number of modules in your plan to work out the total.',guide:'Kojo: “Break the problem into: modules × pieces per module.”',whyItMatters:'Multiplication turns a repeated pattern into a total quantity.',focus:'Multiplication.'},
  14:{title:'Find the Walking-Surface Area',story:'The walking surface behaves like a rectangle in this learning simulation. Use your span and selected width to find its area.',guide:'Kojo: “Length × width tells us how much surface we are planning for.”',whyItMatters:'Area connects dimensions to material quantities.',focus:'Area and multiplication.'},
  15:{title:'How Many Deck Units?',story:'Each fictional deck unit covers a certain area. Divide your planned deck area by the area covered by one unit, then think carefully about a leftover fraction.',guide:'Kojo: “A small uncovered part still needs a whole final unit.”',whyItMatters:'This links area, division and practical rounding.',focus:'Area, division and whole units.'},
  16:{title:'Count the Connection Tokens',story:'The Design Card shows cross-members, connections per cross-member and fictional fastener tokens. Build the total step by step.',guide:'Kojo: “Multiply one layer at a time so you can check your work.”',whyItMatters:'A multi-step product is easier to understand when broken into stages.',focus:'Multi-step multiplication.'},
  17:{title:'Add a Little Extra',story:'Projects often allow for a small amount of waste or breakage. Calculate the displayed percentage of your current deck quantity.',guide:'Kojo: “Turn the percentage into a number you can multiply by the quantity.”',whyItMatters:'Percentages can change physical quantities, not just test scores.',focus:'Percentage allowance.'},
  18:{title:'Buy Whole Packages',story:'Suppliers sell complete packages. If your calculation says 8.8 packages, the shop cannot hand over 8.8 sealed packs.',guide:'Kojo: “Always ask: how many full packages must we actually buy?”',whyItMatters:'Correct package rounding prevents a shortage at the construction site.',focus:'Division and ceiling rounding.'},
  19:{title:'Work Out the Extra Resource',story:'Your bridge system also needs a fictional secondary resource. Use the Design Card rate and the project area to calculate how much to buy.',guide:'Kojo: “Follow the rate on your card — it is simulation data made for this learning adventure.”',whyItMatters:'Rates show how one quantity changes with another.',focus:'Multiplication, area and package conversion.'},
  20:{title:'What Will the Materials Cost?',story:'Turn the quantities in your order into money. Carefully combine the costs for the different material groups.',guide:'Kojo: “Check quantity × price for each group before adding the totals.”',whyItMatters:'Money calculations make planning choices visible in the budget.',focus:'Money, multiplication and addition.'},
  21:{title:'How Many Truck Trips?',story:'Your ordered materials must fit into the fictional delivery vehicle. Divide the total delivery quantity by the vehicle capacity and remember that a partial final load still needs a trip.',guide:'Ama: “If you book too few trips, some of your materials will stay at the supplier.”',whyItMatters:'This calculation directly changes what reaches the site.',focus:'Capacity, division and rounding up.'},
  22:{title:'What Will Delivery Cost?',story:'Each truck trip has a cost. Use the number of trips in your plan and the supplier delivery charge.',guide:'Ama: “Trips × cost per trip gives the transport total.”',whyItMatters:'A logistics decision also changes the budget.',focus:'Money and multiplication.'},
  23:{title:'Plan the Work Cost',story:'The simulation gives a number of workers, days and a daily rate. Combine the three values to find the labour cost.',guide:'Ama: “Think of the cost for one worker, then all workers, across all the days.”',whyItMatters:'Multi-step multiplication helps model repeated costs.',focus:'Schedule and labour cost.'},
  24:{title:'Can the Community Afford the Plan?',story:'Bring materials, transport and labour together, then add the contingency shown in the adventure. Compare your total with the community budget.',guide:'Ama: “Being over budget does not make the bridge collapse — it creates a money problem we must manage.”',whyItMatters:'Different kinds of mistakes should have different consequences.',focus:'Budgeting, percentages and optimisation.'},
  25:{title:'Check What the Trucks Brought',story:'The supplier sends only what your order and transport plan allow. Compare what was needed, what was ordered and what actually arrived.',guide:'Kojo: “Look around the site. Shortages and extra materials should be visible.”',whyItMatters:'Your earlier mathematics now appears as physical-looking project state.',focus:'Interpret delivery and inventory data.'},
  26:{title:'Would You Allow Testing?',story:'Walk around the virtual project and inspect what you can see. Decide whether it is ready for testing or should go back for correction.',guide:'Kojo: “A good inspector does not approve a project just because everyone is excited.”',whyItMatters:'Reasoning can prevent a known problem from reaching the test stage.',focus:'Inspection and logical reasoning.'},
  27:{title:'Normal-Use Test',story:'Begin with ordinary pedestrian use. Watch the simulation carefully instead of expecting instant success or dramatic failure.',guide:'Ama: “Observe first. A small warning can tell you something before a serious problem develops.”',whyItMatters:'Progressive testing helps connect symptoms to stored project decisions.',focus:'Observation and data interpretation.'},
  28:{title:'Busy-Time Test',story:'If normal use is acceptable, gradually increase the simulated crowd toward the scenario peak. Watch movement and how people use the walkway.',guide:'Ama: “The bridge may behave differently when more people arrive.”',whyItMatters:'A design can pass one condition and still reveal a problem in another.',focus:'Interpret peak-use behaviour.'},
  29:{title:'Rain and River Test',story:'Now introduce the fictional seasonal river rise. Environmental clues from your earlier survey may finally matter.',guide:'Ama: “Remember the flood evidence you found at the riverbank?”',whyItMatters:'This closes the loop between early investigation and later consequence.',focus:'Environmental reasoning.'},
  30:{title:'Tell the Story of Your Project',story:'Your notebook already contains most of the evidence. Review the automatically assembled report and add a short reflection about what your mathematics changed.',guide:'Ama: “You do not need to type everything again. Tell us what you learned from the decisions you made.”',whyItMatters:'Reflection helps turn an activity into transferable understanding.',focus:'Review, reflection and project reporting.'},
};
