import { FootbridgeController } from '../../footbridge/useFootbridgeProject';

export default function FootbridgeMission3({ c }: { c: FootbridgeController }) {
  const s = c.state.scenario;
  const task = (id:number) => c.recordFor(id).completed ? 'project-action complete' : 'project-action';
  const selected = c.state.selectedBridgeSystem ? s.designCards[c.state.selectedBridgeSystem] : null;

  return <div className="project-mission-content">
    <div className="mission-narrative"><span>🧩 MISSION 3 · CHOOSE YOUR BRIDGE</span><h2>Three bridge ideas. Which one fits your community?</h2><p>There is no one bridge that wins every time. Compare the three Mezzo Design Cards and choose the idea that makes the most sense for this adventure. The numbers are fictional learning data, not real engineering instructions.</p></div>
    <div className="design-card-grid">{Object.values(s.designCards).map(card=><button key={card.id} type="button" className={c.state.selectedBridgeSystem===card.id?'selected':''} onClick={()=>c.setState(current=>({...current,selectedBridgeSystem:card.id}))}><strong>🌉 {card.name}</strong><span>{card.summary}</span><small>💰 Cost {card.relativeCost}/5 · 🚚 Moving it {card.transportDifficulty}/5 · 🔧 Care {card.maintenanceLevel}/5 · ⏱️ Build time {card.constructionTime}/5 · 📦 Availability {card.availability}/5 · 🌿 Environment {card.environmentalSuitability}/5</small></button>)}</div>
    <article className={task(10)}><div><span>💬 Tell Ama and Kojo why</span><h3>Why do you think your chosen bridge idea suits this challenge?</h3></div>{selected&&<div className="evidence-strip"><b>Your choice:</b> {selected.name}<b>Money available:</b> GHS {s.communityBudget.toLocaleString()}<b>Truck capacity:</b> {s.vehicleCapacityUnits} simulation delivery units</div>}<textarea rows={4} value={c.response('10-reason')} onChange={e=>c.setResponse('10-reason',e.target.value)} placeholder="You can talk about money, transport, availability, build time or the environment..."/><button className="btn btn-primary" type="button" disabled={!selected} onClick={()=>{if(!selected)return; const reason=c.response('10-reason').trim(); const ok=reason.length>=12; if(!ok)return c.setDecisionFeedback(10,'Tell us a little more about why you chose this bridge idea.'); c.recordAttempt(10,selected.id,true,{completeOnAttempt:true,notebookSection:'DESIGN_DECISIONS',notebookEntry:`${selected.name} selected. Learner justification: ${reason}`}); c.setDecisionFeedback(10,'⭐ Nice choice! Your reason is saved. Now your bridge idea can move to the materials stage.');}}>Choose this bridge idea</button>{c.feedback[10]&&<p className="action-feedback">{c.feedback[10]}</p>}</article>
    {c.missionComplete(3)&&<button className="mission-advance" type="button" onClick={c.unlockNextMission}>📦 Bridge idea chosen! Kojo says: “Now let’s work out what we need to build it.” →</button>}
  </div>;
}
