import { budgetFromRecordedCosts, correctLabourCost, orderedDeliveryUnits, selectedSupplier, transportCostForTrips, tripsRequiredForOrders } from '../../footbridge/mathEngine';
import { FootbridgeController } from '../../footbridge/useFootbridgeProject';

export default function FootbridgeMission5({ c }: { c: FootbridgeController }) {
  const state=c.state;
  const s=state.scenario;
  const task=(id:number)=>c.recordFor(id).completed?'project-action complete':'project-action';
  const supplier=selectedSupplier(state);
  const deliveryUnits=orderedDeliveryUnits(state);
  const tripsExpected=tripsRequiredForOrders(state);
  const labourExpected=correctLabourCost(state);
  const hint=(id:number,levels:string[])=>{const level=c.recordFor(id).highestHintLevel;return level?levels[Math.min(level,levels.length)-1]:'';};
  const num=(key:string|number,placeholder:string)=><input type="number" inputMode="decimal" value={c.response(key)} onChange={e=>c.setResponse(key,e.target.value)} placeholder={placeholder}/>;
  const working=(id:number)=><textarea rows={2} value={c.working[id]??''} onChange={e=>c.setWorkingText(id,e.target.value)} placeholder="Working board (optional)"/>;
  const finite=(key:string|number)=>c.response(key)!==''&&Number.isFinite(Number(c.response(key)));
  const budget=statusBudget(state.totalCost,s.communityBudget);

  return <div className="project-mission-content">
    <div className="mission-narrative"><span>Mission 5 · Project management</span><h2>Plan deliveries, labour and the complete project budget.</h2><p>The quantities you ordered in procurement now drive transport. If you schedule too few trips, the simulation will leave some materials at the supplier instead of silently correcting your plan.</p></div>
    <div className="design-data-board"><article><span>Ordered delivery units</span><strong>{deliveryUnits}</strong></article><article><span>Vehicle capacity</span><strong>{s.vehicleCapacityUnits}</strong></article><article><span>Supplier</span><strong>{supplier.name}</strong></article><article><span>Community budget</span><strong>GHS {s.communityBudget.toLocaleString()}</strong></article></div>

    <article className={task(21)}><div><span>Transport requirements</span><h3>Your order contains {deliveryUnits} simulation delivery units. Each virtual vehicle can carry {s.vehicleCapacityUnits}. How many whole trips will you schedule?</h3></div>{working(21)}{num(21,'Whole transport trips')}<div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{if(!finite(21))return c.setDecisionFeedback(21,'Enter a whole number of trips.');const a=Number(c.response(21));const ok=a===tripsExpected;c.setState(current=>({...current,tripsOrdered:a}));c.recordAttempt(21,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'TRANSPORT_CAPACITY_ERROR',notebookSection:'TRANSPORT',notebookEntry:`Transport trips scheduled: ${a}; virtual vehicle capacity ${s.vehicleCapacityUnits} units/trip.`});c.setDecisionFeedback(21,ok?'Transport requirement calculated correctly.':'Trip schedule recorded. If it is too small, some ordered materials will remain at the supplier during Mission 6.');}}>Schedule trips</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(21)}>Hint</button></div>{hint(21,['Can a fraction of a delivery trip bring the remaining materials?','Divide the ordered delivery units by the vehicle capacity.','Trips = ceiling(total delivery units ÷ capacity per trip).','Any fractional result must be rounded upward to the next complete trip.'])&&<p className="hint-box">{hint(21,['Can a fraction of a delivery trip bring the remaining materials?','Divide the ordered delivery units by the vehicle capacity.','Trips = ceiling(total delivery units ÷ capacity per trip).','Any fractional result must be rounded upward to the next complete trip.'])}</p>}{c.feedback[21]&&<p className="action-feedback">{c.feedback[21]}</p>}</article>

    <article className={task(22)}><div><span>Transportation cost</span><h3>{supplier.name} charges GHS {supplier.deliveryCostPerTrip} for each virtual delivery trip. Calculate the transport cost for the {state.tripsOrdered??0} trip(s) you scheduled.</h3></div>{working(22)}{num(22,'Transport cost (GHS)')}<div className="task-buttons"><button className="btn btn-primary" type="button" disabled={state.tripsOrdered===undefined} onClick={()=>{if(!finite(22))return c.setDecisionFeedback(22,'Enter your transport cost.');const a=Number(c.response(22));const expected=transportCostForTrips(state);const ok=Math.abs(a-expected)<=.01;c.setState(current=>({...current,transportCost:a}));c.recordAttempt(22,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'MULTIPLICATION_ERROR',notebookSection:'TRANSPORT',notebookEntry:`Transport cost recorded: GHS ${a.toFixed(2)}.`});c.setDecisionFeedback(22,ok?'Transport cost matches your scheduled trips.':'Cost recorded. This creates a financial discrepancy only; it does not directly cause structural failure.');}}>Record transport cost</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(22)}>Hint</button></div>{hint(22,['How many trips did you decide to schedule?','Use the supplier’s cost per trip shown above.','Transport cost = scheduled trips × cost per trip.','Multiply your trip count by the displayed GHS cost per trip.'])&&<p className="hint-box">{hint(22,['How many trips did you decide to schedule?','Use the supplier’s cost per trip shown above.','Transport cost = scheduled trips × cost per trip.','Multiply your trip count by the displayed GHS cost per trip.'])}</p>}{c.feedback[22]&&<p className="action-feedback">{c.feedback[22]}</p>}</article>

    <article className={task(23)}><div><span>Labour and schedule cost</span><h3>The fictional schedule assigns {s.labourWorkers} workers for {s.labourDays} days at GHS {s.labourDailyRate} per worker per day. Calculate the labour cost.</h3></div>{working(23)}{num(23,'Labour cost (GHS)')}<div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{if(!finite(23))return c.setDecisionFeedback(23,'Enter your labour cost.');const a=Number(c.response(23));const ok=Math.abs(a-labourExpected)<=.01;c.setState(current=>({...current,labourCost:a}));c.recordAttempt(23,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'MULTIPLICATION_ERROR',notebookSection:'BUDGET',notebookEntry:`Labour cost recorded by learner: GHS ${a.toFixed(2)}.`});c.setDecisionFeedback(23,ok?'Labour cost is correct.':'Labour cost recorded. An error here affects the budget and schedule report, not bridge stability.');}}>Record labour cost</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(23)}>Hint</button></div>{hint(23,['What does one worker cost across all project days?','Multiply workers by days before applying the daily rate.','Labour cost = workers × days × daily rate.','Multiply the three values shown in the schedule card.'])&&<p className="hint-box">{hint(23,['What does one worker cost across all project days?','Multiply workers by days before applying the daily rate.','Labour cost = workers × days × daily rate.','Multiply the three values shown in the schedule card.'])}</p>}{c.feedback[23]&&<p className="action-feedback">{c.feedback[23]}</p>}</article>

    <article className={task(24)}><div><span>Complete project budget</span><h3>Prepare the complete budget using the costs you have recorded and a {Math.round(s.contingencyRate*100)}% contingency.</h3></div><div className="budget-lines"><span>Materials recorded: <b>GHS {(state.materialCost??0).toFixed(2)}</b></span><span>Transport recorded: <b>GHS {(state.transportCost??0).toFixed(2)}</b></span><span>Labour recorded: <b>GHS {(state.labourCost??0).toFixed(2)}</b></span><span>Community budget: <b>GHS {s.communityBudget.toFixed(2)}</b></span></div>{working(24)}{num('24-contingency','Contingency amount (GHS)')}{num(24,'Complete project total (GHS)')}<div className="task-buttons"><button className="btn btn-primary" type="button" disabled={state.materialCost===undefined||state.transportCost===undefined||state.labourCost===undefined} onClick={()=>{if(!finite('24-contingency')||!finite(24))return c.setDecisionFeedback(24,'Enter both the contingency amount and complete project total.');const reference=budgetFromRecordedCosts(state);const contingency=Number(c.response('24-contingency'));const total=Number(c.response(24));const ok=Math.abs(contingency-reference.contingency)<=.02&&Math.abs(total-reference.total)<=.02;c.setState(current=>({...current,contingency,totalCost:total}));c.recordAttempt(24,`contingency:${contingency};total:${total}`,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'BUDGET_TOTAL_ERROR',notebookSection:'BUDGET',notebookEntry:`Project budget submitted: contingency GHS ${contingency.toFixed(2)}, total GHS ${total.toFixed(2)} against community budget GHS ${s.communityBudget.toFixed(2)}.`});c.setDecisionFeedback(24,ok?`Budget arithmetic is consistent. Status: ${statusBudget(total,s.communityBudget)}.`:`Budget recorded. There is a calculation discrepancy; the financial report will retain it. Current submitted status: ${statusBudget(total,s.communityBudget)}.`);}}>Submit project budget</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(24)}>Hint</button></div>{hint(24,['Start by adding materials, transport and labour.','Calculate the stated contingency percentage from that subtotal.','Total project cost = subtotal + contingency.','Contingency = subtotal × rate; then add it to the subtotal.'])&&<p className="hint-box">{hint(24,['Start by adding materials, transport and labour.','Calculate the stated contingency percentage from that subtotal.','Total project cost = subtotal + contingency.','Contingency = subtotal × rate; then add it to the subtotal.'])}</p>}{c.feedback[24]&&<p className="action-feedback">{c.feedback[24]}</p>}{state.totalCost!==undefined&&<div className={`budget-status ${budget.toLowerCase().replace(/ /g,'-')}`}><strong>{budget}</strong><span>Your submitted total: GHS {state.totalCost.toFixed(2)}</span></div>}</article>

    {c.missionComplete(5)&&<button className="mission-advance" type="button" onClick={c.unlockNextMission}>Project plan approved for delivery. Move to construction and inspection →</button>}
  </div>;
}

function statusBudget(total:number|undefined,budget:number){
  if(total===undefined)return 'NOT YET SUBMITTED';
  if(total<=budget)return 'WITHIN BUDGET';
  const over=(total-budget)/budget;
  if(over<=.08)return 'SLIGHTLY OVER BUDGET';
  return 'SERIOUSLY OVER BUDGET';
}
