import { canonicalProcurementRequirements, deckPackageSize, learnerCalculationTargets, materialCostFromOrders, plannedPackageRequirements, roundTo } from '../../footbridge/mathEngine';
import { FootbridgeController } from '../../footbridge/useFootbridgeProject';

export default function FootbridgeMission4({ c }: { c: FootbridgeController }) {
  const state = c.state;
  const s = state.scenario;
  const task = (id:number) => c.recordFor(id).completed ? 'project-action complete' : 'project-action';
  if (!state.selectedBridgeSystem) return <div className="project-mission-content"><div className="locked-note">Return to Mission 3 and select a simulation bridge system before procurement.</div></div>;
  const card = s.designCards[state.selectedBridgeSystem];
  const target = learnerCalculationTargets(state)!;
  const trueRequirement = canonicalProcurementRequirements(state)!;
  const packagePlan = plannedPackageRequirements(state)!;
  const hint = (id:number, levels:string[]) => { const level=c.recordFor(id).highestHintLevel; return level?levels[Math.min(level,levels.length)-1]:''; };
  const num = (key:string|number, placeholder:string) => <input type="number" inputMode="decimal" value={c.response(key)} onChange={e=>c.setResponse(key,e.target.value)} placeholder={placeholder}/>;
  const working = (id:number) => <textarea rows={2} value={c.working[id]??''} onChange={e=>c.setWorkingText(id,e.target.value)} placeholder="Working board (optional)"/>;
  const finite = (key:string|number) => c.response(key)!=='' && Number.isFinite(Number(c.response(key)));

  const plannedModules = state.calculatedQuantities.modules ?? target.modules;
  const expectedPrimaryFromPlan = plannedModules * card.memberUnitsPerModule;
  const plannedArea = state.calculatedQuantities.deckArea ?? target.deckArea;
  const expectedDeckFromPlan = Math.ceil(plannedArea / card.deckUnitArea);
  const expectedConnectionsFromPlan = plannedModules * card.crossMembersPerModule * card.connectionsPerCrossMember * card.fastenersPerConnection;
  const plannedDeckUnits = state.calculatedQuantities.deckUnits ?? expectedDeckFromPlan;
  const expectedAllowanceFromPlan = Math.ceil(plannedDeckUnits * s.allowanceRate);
  const plannedSecondaryBase = plannedArea * card.secondaryResourcePerSquareMetre;
  const expectedSecondaryPackages = Math.ceil(plannedSecondaryBase / card.secondaryPackageSize);

  const designComponents: Record<string,string> = {
    timber: 'Longitudinal members · cross-members · deck boards · connection tokens',
    steel: 'Longitudinal members · cross-members · deck panels · connection tokens',
    'reinforced-concrete': 'Simulation deck units · support components · connection tokens · Mezzo simulation resource',
  };

  function saveTrueRequirements() {
    c.setState(current=>({
      ...current,
      materialsRequired: {
        ...current.materialsRequired,
        primary: trueRequirement.primaryUnits,
        deck: trueRequirement.deckUnits,
        connections: trueRequirement.connections,
        secondary: trueRequirement.secondaryBaseUnits,
      },
    }));
  }

  return <div className="project-mission-content">
    <div className="mission-narrative"><span>Mission 4 · Procurement office</span><h2>Turn the design into quantities, packages and an order.</h2><p>Your own survey measurements and recorded width now drive the planning calculations. Wrong arithmetic is not silently corrected: it can create shortages, excess materials or extra cost later.</p></div>
    <div className="design-data-board"><article><span>Your design span</span><strong>{target.span} m</strong></article><article><span>Your design width</span><strong>{target.width} m</strong></article><article><span>System</span><strong>{card.name.replace(' Bridge System','')}</strong></article><article><span>Allowance</span><strong>{Math.round(s.allowanceRate*100)}%</strong></article></div>
    <div className="simulation-safety-notice"><strong>Mezzo Design Card</strong><span>All dimensions, component relationships, package sizes and resource rates below are fictional educational simulation data. They are not real construction specifications.</span></div>

    <article className={task(11)}><div><span>Interpret the design drawing</span><h3>Identify the component family shown on the {card.name} Design Card.</h3></div><div className="choice-grid">{Object.entries(designComponents).map(([id,label])=><button key={id} type="button" onClick={()=>{const ok=id===state.selectedBridgeSystem; saveTrueRequirements(); c.recordAttempt(11,id,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'DATA_INTERPRETATION_ERROR',notebookSection:'PROCUREMENT',notebookEntry:`Design drawing interpretation selected: ${label}.`}); c.setDecisionFeedback(11,ok?'You identified the component family on the selected Design Card.':'Interpretation recorded. Recheck which Design Card your planning committee approved.');}}>{label}</button>)}</div>{c.feedback[11]&&<p className="action-feedback">{c.feedback[11]}</p>}</article>

    <article className={task(12)}><div><span>Virtual design modules</span><h3>Your design span is {target.span} m and one fictional module covers {card.moduleLength} m. How many complete modules must the plan provide?</h3></div>{working(12)}{num(12,'Whole modules')}<div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{if(!finite(12))return c.setDecisionFeedback(12,'Enter a whole-number module quantity.'); const a=Number(c.response(12)); const ok=a===target.modules; c.updateCalculatedQuantity('modules',a); c.recordAttempt(12,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'ROUNDING_PACK_SIZE_ERROR',notebookSection:'CALCULATIONS',notebookEntry:`Design modules planned: ${a}.`}); c.setDecisionFeedback(12,ok?'Module quantity is correct.':'Quantity recorded. Remember that a partial final module still requires a complete module.');}}>Record module plan</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(12)}>Hint</button></div>{hint(12,['Will a fraction of a module complete the crossing?','Divide your recorded design span by the fictional module length.','Modules = ceiling(design span ÷ module length).','Always round the module count upward to a whole module.'])&&<p className="hint-box">{hint(12,['Will a fraction of a module complete the crossing?','Divide your recorded design span by the fictional module length.','Modules = ceiling(design span ÷ module length).','Always round the module count upward to a whole module.'])}</p>}{c.feedback[12]&&<p className="action-feedback">{c.feedback[12]}</p>}</article>

    <article className={task(13)}><div><span>Primary member schedule</span><h3>Your current plan contains {plannedModules} module(s). The Design Card assigns {card.memberUnitsPerModule} primary member units per module. Calculate the primary units in your schedule.</h3></div>{working(13)}{num(13,'Primary member units')}<div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{if(!finite(13))return c.setDecisionFeedback(13,'Enter your primary member quantity.'); const a=Number(c.response(13)); const ok=a===expectedPrimaryFromPlan; c.updateCalculatedQuantity('primaryUnits',a); c.recordAttempt(13,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'MULTIPLICATION_ERROR',notebookSection:'CALCULATIONS',notebookEntry:`Primary member schedule: ${a} units.`}); c.setDecisionFeedback(13,ok?'Primary member multiplication is correct.':'Quantity recorded. It will carry forward into package planning, so recheck your multiplication if needed.');}}>Record member schedule</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(13)}>Hint</button></div>{hint(13,['How many member units belong to each module?','Use the module count currently in your project plan.','Primary units = planned modules × member units per module.','Multiply the two values shown above.'])&&<p className="hint-box">{hint(13,['How many member units belong to each module?','Use the module count currently in your project plan.','Primary units = planned modules × member units per module.','Multiply the two values shown above.'])}</p>}{c.feedback[13]&&<p className="action-feedback">{c.feedback[13]}</p>}</article>

    <article className={task(14)}><div><span>Deck area</span><h3>Calculate the planned deck area using your recorded span ({target.span} m) and width ({target.width} m).</h3></div>{working(14)}{num(14,'Deck area in m²')}<div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{if(!finite(14))return c.setDecisionFeedback(14,'Enter the calculated deck area.'); const a=Number(c.response(14)); const ok=Math.abs(a-target.deckArea)<=.02; c.updateCalculatedQuantity('deckArea',a); c.recordAttempt(14,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'AREA_ERROR',notebookSection:'CALCULATIONS',notebookEntry:`Deck area planned: ${a} m².`}); c.setDecisionFeedback(14,ok?'Area calculation is correct for your recorded design dimensions.':'Area recorded. Recheck length × width before procurement.');}}>Record deck area</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(14)}>Hint</button></div>{hint(14,['Which two dimensions describe the rectangular walkway surface?','Use your recorded design span and selected width.','Deck area = design span × design width.','Multiply the two metre measurements; the result is in square metres.'])&&<p className="hint-box">{hint(14,['Which two dimensions describe the rectangular walkway surface?','Use your recorded design span and selected width.','Deck area = design span × design width.','Multiply the two metre measurements; the result is in square metres.'])}</p>}{c.feedback[14]&&<p className="action-feedback">{c.feedback[14]}</p>}</article>

    <article className={task(15)}><div><span>Deck-material quantity</span><h3>Your current deck area is {plannedArea} m². Each fictional {state.selectedBridgeSystem==='timber'?'board group':state.selectedBridgeSystem==='steel'?'panel':'deck unit'} covers {card.deckUnitArea} m². How many whole deck units are required?</h3></div>{working(15)}{num(15,'Whole deck units')}<div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{if(!finite(15))return c.setDecisionFeedback(15,'Enter a whole deck-unit quantity.'); const a=Number(c.response(15)); const ok=a===expectedDeckFromPlan; c.updateCalculatedQuantity('deckUnits',a); c.recordAttempt(15,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'DIVISION_ERROR',notebookSection:'CALCULATIONS',notebookEntry:`Deck-material schedule: ${a} units.`}); c.setDecisionFeedback(15,ok?'Deck quantity is correct for your planned area.':'Quantity recorded. A fractional final deck unit must be rounded up to a whole unit.');}}>Record deck quantity</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(15)}>Hint</button></div>{hint(15,['Can you purchase part of an indivisible deck unit?','Divide the planned area by the area covered by one unit.','Deck units = ceiling(deck area ÷ area per deck unit).','Round any fractional result upward to a whole unit.'])&&<p className="hint-box">{hint(15,['Can you purchase part of an indivisible deck unit?','Divide the planned area by the area covered by one unit.','Deck units = ceiling(deck area ÷ area per deck unit).','Round any fractional result upward to a whole unit.'])}</p>}{c.feedback[15]&&<p className="action-feedback">{c.feedback[15]}</p>}</article>

    <article className={task(16)}><div><span>Connection schedule</span><h3>For each planned module the card shows {card.crossMembersPerModule} cross-members, {card.connectionsPerCrossMember} connections per cross-member and {card.fastenersPerConnection} fictional fastener tokens per connection. Determine the total.</h3></div>{working(16)}{num(16,'Connection/fastener tokens')}<div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{if(!finite(16))return c.setDecisionFeedback(16,'Enter your connection-token quantity.'); const a=Number(c.response(16)); const ok=a===expectedConnectionsFromPlan; c.updateCalculatedQuantity('connections',a); c.setState(current=>({...current,materialsOrdered:{...current.materialsOrdered,connections:a}})); c.recordAttempt(16,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'MULTIPLICATION_ERROR',notebookSection:'CALCULATIONS',notebookEntry:`Connection schedule: ${a} fictional fastener tokens.`}); c.setDecisionFeedback(16,ok?'Connection calculation is correct.':'Quantity recorded. This number will become the connection tokens ordered, so an undercount may later be visible during testing.');}}>Record connections</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(16)}>Hint</button></div>{hint(16,['Break the calculation into stages rather than multiplying mentally all at once.','Start with planned modules × cross-members per module.','Then multiply by connections per cross-member and fasteners per connection.','Total = modules × cross-members × connections × fasteners.'])&&<p className="hint-box">{hint(16,['Break the calculation into stages rather than multiplying mentally all at once.','Start with planned modules × cross-members per module.','Then multiply by connections per cross-member and fasteners per connection.','Total = modules × cross-members × connections × fasteners.'])}</p>}{c.feedback[16]&&<p className="action-feedback">{c.feedback[16]}</p>}</article>

    <article className={task(17)}><div><span>Waste/breakage allowance</span><h3>The project allowance is {Math.round(s.allowanceRate*100)}%. Your current deck schedule contains {plannedDeckUnits} units. How many additional whole units should the allowance add?</h3></div>{working(17)}{num(17,'Allowance units')}<div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{if(!finite(17))return c.setDecisionFeedback(17,'Enter the additional allowance units.'); const a=Number(c.response(17)); const ok=a===expectedAllowanceFromPlan; c.updateCalculatedQuantity('deckAllowanceUnits',a); c.recordAttempt(17,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'PERCENTAGE_ERROR',notebookSection:'CALCULATIONS',notebookEntry:`Deck allowance added by learner: ${a} units.`}); c.setDecisionFeedback(17,ok?'Allowance calculation is correct.':'Allowance recorded. Recheck the percentage and remember that an indivisible extra unit must be whole.');}}>Record allowance</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(17)}>Hint</button></div>{hint(17,['What is the stated percentage of your current deck-unit schedule?','Convert the percentage to a decimal before multiplying.','Allowance = deck units × allowance rate, then round up to a whole unit.','Multiply by the displayed allowance percentage and use the next whole unit when necessary.'])&&<p className="hint-box">{hint(17,['What is the stated percentage of your current deck-unit schedule?','Convert the percentage to a decimal before multiplying.','Allowance = deck units × allowance rate, then round up to a whole unit.','Multiply by the displayed allowance percentage and use the next whole unit when necessary.'])}</p>}{c.feedback[17]&&<p className="action-feedback">{c.feedback[17]}</p>}</article>

    <article className={task(18)}><div><span>Whole-package purchasing</span><h3>Convert your planned quantities into complete purchase packages.</h3></div><div className="procurement-table"><div><b>Primary members</b><span>Plan: {packagePlan.plannedPrimary} units</span><span>{packagePlan.primaryPackageSize} per package</span>{num('18-primary','Primary packages')}</div><div><b>Deck material</b><span>Plan + your allowance: {packagePlan.plannedDeck + packagePlan.plannedAllowance} units</span><span>{packagePlan.deckPackageSize} per package</span>{num('18-deck','Deck packages')}</div></div><div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{if(!finite('18-primary')||!finite('18-deck'))return c.setDecisionFeedback(18,'Enter whole package counts for both materials.'); const pp=Number(c.response('18-primary')); const dp=Number(c.response('18-deck')); const ok=pp===packagePlan.primaryPackages&&dp===packagePlan.deckPackages; c.setState(current=>({...current,packagesOrdered:{...current.packagesOrdered,primary:pp,deck:dp},materialsOrdered:{...current.materialsOrdered,primary:pp*card.primaryPackageSize,deck:dp*deckPackageSize(current)}})); c.recordAttempt(18,`primary:${pp};deck:${dp}`,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'ROUNDING_PACK_SIZE_ERROR',notebookSection:'MATERIAL_ORDERS',notebookEntry:`Packages ordered: ${pp} primary packages and ${dp} deck packages.`}); c.setDecisionFeedback(18,ok?'Whole-package conversion is correct.':'Order recorded. Packages cannot be fractional; too few packages may create a visible shortage and extra packages will remain unused.');}}>Place package order</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(18)}>Hint</button></div>{hint(18,['Can the supplier sell 8.4 sealed packages?','Divide each planned quantity by its package size.','Packages = ceiling(quantity needed ÷ units per package).','Round every non-whole package result upward, not to the nearest whole number.'])&&<p className="hint-box">{hint(18,['Can the supplier sell 8.4 sealed packages?','Divide each planned quantity by its package size.','Packages = ceiling(quantity needed ÷ units per package).','Round every non-whole package result upward, not to the nearest whole number.'])}</p>}{c.feedback[18]&&<p className="action-feedback">{c.feedback[18]}</p>}</article>

    <article className={task(19)}><div><span>Secondary resource</span><h3>The fictional Design Card uses {card.secondaryResourcePerSquareMetre} resource units per m² of your planned deck area. The resource is supplied in packages of {card.secondaryPackageSize}. How many whole packages will you order?</h3></div><div className="evidence-strip"><b>Planned area:</b> {plannedArea} m² <b>Calculated base resource:</b> {roundTo(plannedSecondaryBase,2)} units</div>{working(19)}{num(19,'Secondary-resource packages')}<div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{if(!finite(19))return c.setDecisionFeedback(19,'Enter the whole package quantity.'); const p=Number(c.response(19)); const ok=p===expectedSecondaryPackages; c.updateCalculatedQuantity('secondaryPackages',p); c.setState(current=>({...current,packagesOrdered:{...current.packagesOrdered,secondary:p},materialsOrdered:{...current.materialsOrdered,secondary:p*card.secondaryPackageSize}})); c.recordAttempt(19,p,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'ROUNDING_PACK_SIZE_ERROR',notebookSection:'MATERIAL_ORDERS',notebookEntry:`Secondary resource ordered: ${p} packages (${p*card.secondaryPackageSize} units).`}); c.setDecisionFeedback(19,ok?'Secondary-resource package calculation is correct.':'Order recorded. The environmental/durability simulation will later see the quantity you actually purchased.');}}>Order secondary resource</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(19)}>Hint</button></div>{hint(19,['First determine the resource units needed for your planned area.','Multiply planned area by resource units per square metre.','Then divide by package size and round upward to a whole package.','Packages = ceiling((area × resource rate) ÷ package size).'])&&<p className="hint-box">{hint(19,['First determine the resource units needed for your planned area.','Multiply planned area by resource units per square metre.','Then divide by package size and round upward to a whole package.','Packages = ceiling((area × resource rate) ÷ package size).'])}</p>}{c.feedback[19]&&<p className="action-feedback">{c.feedback[19]}</p>}</article>

    <article className={task(20)}><div><span>Virtual supplier/material shop</span><h3>Choose a supplier for delivery and calculate the cost of the materials you actually ordered.</h3></div><div className="supplier-grid">{s.suppliers.map(supplier=><button key={supplier.id} type="button" className={state.selectedSupplierId===supplier.id?'selected':''} onClick={()=>c.setState(current=>({...current,selectedSupplierId:supplier.id}))}><strong>{supplier.name}</strong><span>Delivery: GHS {supplier.deliveryCostPerTrip}/trip</span><small>Availability {supplier.availabilityRating}/5</small></button>)}</div><div className="price-board"><span>Primary: GHS {card.primaryUnitPrice}/unit</span><span>Deck: GHS {card.deckUnitPrice}/unit</span><span>Connections: GHS {card.connectionUnitPrice}/token</span><span>Secondary: GHS {card.secondaryUnitPrice}/unit</span></div>{working(20)}{num(20,'Total material order cost (GHS)')}<div className="task-buttons"><button className="btn btn-primary" type="button" disabled={!state.selectedSupplierId} onClick={()=>{if(!finite(20))return c.setDecisionFeedback(20,'Choose a supplier and enter the material order cost.'); const a=Number(c.response(20)); const expected=materialCostFromOrders(state); const ok=Math.abs(a-expected)<=.01; c.setState(current=>({...current,materialCost:a})); c.recordAttempt(20,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'PROCUREMENT_ERROR',notebookSection:'PROCUREMENT',notebookEntry:`Material cost recorded by learner: GHS ${a.toFixed(2)}. Supplier: ${s.suppliers.find(x=>x.id===state.selectedSupplierId)?.name}.`}); c.setDecisionFeedback(20,ok?'Material order cost matches the quantities you ordered.':'Cost recorded. A costing error will affect the financial report, not randomly damage the bridge.');}}>Confirm procurement cost</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(20)}>Hint</button></div>{hint(20,['Use the quantities you actually ordered, not only the minimum required quantities.','Multiply each ordered quantity by its displayed unit price.','Material cost = primary cost + deck cost + connection cost + secondary-resource cost.','Calculate each line separately, then add the four line totals.'])&&<p className="hint-box">{hint(20,['Use the quantities you actually ordered, not only the minimum required quantities.','Multiply each ordered quantity by its displayed unit price.','Material cost = primary cost + deck cost + connection cost + secondary-resource cost.','Calculate each line separately, then add the four line totals.'])}</p>}{c.feedback[20]&&<p className="action-feedback">{c.feedback[20]}</p>}</article>

    {c.missionComplete(4)&&<button className="mission-advance" type="button" onClick={c.unlockNextMission}>Your procurement schedule is complete. Report to project management →</button>}
  </div>;
}
