import { FootbridgeController } from '../../footbridge/useFootbridgeProject';

function tolerance(level: number) { return level === 1 ? 0.2 : level === 3 ? 0.05 : 0.1; }

export default function FootbridgeMission2({ c }: { c: FootbridgeController }) {
  const s = c.state.scenario;
  const selectedSite = s.sites.find(site => site.id === c.state.selectedSiteId);
  const task = (id:number) => c.recordFor(id).completed ? 'project-action complete' : 'project-action';
  const scoreSite = (site: typeof s.sites[number]) => site.accessRating + site.environmentalRating + site.convenienceRating - site.spanMetres * .08 - site.costFactor;
  const bestSite = [...s.sites].sort((a,b)=>scoreSite(b)-scoreSite(a))[0];
  const hint = (id:number, levels:string[]) => { const level=c.recordFor(id).highestHintLevel; return level?levels[Math.min(level,levels.length)-1]:''; };

  return <div className="project-mission-content">
    <div className="mission-narrative"><span>🌊 MISSION 2 · EXPLORE THE RIVER</span><h2>Grab your tools — it is time to investigate the crossing.</h2><p>Kojo has brought you to the riverbank. Compare possible crossing spots, measure carefully, look for flood clues and make a simple scale plan.</p></div>

    <article className={task(5)}><div><span>📍 Pick a crossing spot</span><h3>Which place looks best overall for helping both communities?</h3></div><div className="site-grid">{s.sites.map(site=><button key={site.id} type="button" className={c.state.selectedSiteId===site.id?'selected':''} onClick={()=>c.setState(current=>({...current,selectedSiteId:site.id}))}><strong>{site.name}</strong><span>{site.narrative}</span><small>🚶 Access {site.accessRating}/5 · 🌿 Environment {site.environmentalRating}/5 · 🏘️ Convenience {site.convenienceRating}/5 · 💰 Cost level {site.costFactor.toFixed(2)}</small></button>)}</div><textarea rows={3} value={c.response('5-reason')} onChange={e=>c.setResponse('5-reason',e.target.value)} placeholder="Tell us why you chose this spot..."/><button className="btn btn-primary" type="button" disabled={!selectedSite} onClick={()=>{if(!selectedSite)return; const reason=c.response('5-reason').trim(); if(reason.length<10)return c.setDecisionFeedback(5,'Tell us a little more about why this place is a good choice.'); const correct=selectedSite.id===bestSite.id; c.recordAttempt(5,selectedSite.id,correct,{completeOnAttempt:true,misconceptionTag:correct?undefined:'LOGICAL_REASONING_ERROR',notebookSection:'SITE_SURVEY',notebookEntry:`Crossing selected: ${selectedSite.name}. Learner justification: ${reason}`}); c.setDecisionFeedback(5,correct?'⭐ Great choice! This spot gives a strong balance in this adventure.':'Your choice is saved. Another spot balances the clues a little better, but your project can continue with the place you chose.');}}>Choose this crossing</button>{c.feedback[5]&&<p className="action-feedback">{c.feedback[5]}</p>}</article>

    <article className={task(6)}><div><span>📏 Measure the river</span><h3>Use the riverbank markers to work out how far the bridge must cross.</h3></div>{!selectedSite?<p className="locked-note">Choose a crossing spot first.</p>:<><div className="survey-tool"><span>🏁 Bank A</span><i/><span>🏁 Bank B</span><small>The answer is hidden. In VR you will measure it yourself; this control is the desktop/tablet version.</small></div><input type="number" inputMode="decimal" value={c.response(6)} onChange={e=>c.setResponse(6,e.target.value)} placeholder="Your measurement in simulation metres"/><div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{const a=Number(c.response(6)); if(!Number.isFinite(a)||a<=0||c.response(6)==='')return c.setDecisionFeedback(6,'Take a measurement before leaving the riverbank.'); const ok=Math.abs(a-selectedSite.spanMetres)<=tolerance(s.difficultyLevel); c.setState(current=>({...current,riverSpanStudent:a})); c.recordAttempt(6,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'MEASUREMENT_ERROR',notebookSection:'MEASUREMENTS',notebookEntry:`Learner river measurement: ${a} simulation m at ${selectedSite.name}.`}); c.setDecisionFeedback(6,ok?'⭐ Nice measuring! Your reading is within the allowed range.':'Your measurement is saved. It may affect later calculations, so you can revisit it if you think the endpoints were not lined up carefully.');}}>Save my measurement</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(6)}>💡 Give me a hint</button></div>{hint(6,['Check that both ends of the measuring tool touch the marked riverbanks.','Measure straight across the proposed crossing, not along the riverbank.','Look carefully at both endpoints before you record the number.','Reset the tool between the two marked bank points and take a fresh reading.'])&&<p className="hint-box">{hint(6,['Check that both ends of the measuring tool touch the marked riverbanks.','Measure straight across the proposed crossing, not along the riverbank.','Look carefully at both endpoints before you record the number.','Reset the tool between the two marked bank points and take a fresh reading.'])}</p>}</>}{c.feedback[6]&&<p className="action-feedback">{c.feedback[6]}</p>}</article>

    <article className={task(7)}><div><span>📋 Read the mission brief</span><h3>The community asks for a walkway width of <b>{s.walkwayRequirementMetres} simulation m</b>. What width will you carry into your plan?</h3></div><input type="number" inputMode="decimal" value={c.response(7)} onChange={e=>c.setResponse(7,e.target.value)} placeholder="Walkway width"/><button className="btn btn-primary" type="button" onClick={()=>{const a=Number(c.response(7)); if(!Number.isFinite(a)||a<=0||c.response(7)==='')return c.setDecisionFeedback(7,'Enter the width you want to carry into your plan.'); const ok=Math.abs(a-s.walkwayRequirementMetres)<.01; c.setState(current=>({...current,walkwaySelected:a})); c.recordAttempt(7,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'DATA_INTERPRETATION_ERROR',notebookSection:'MEASUREMENTS',notebookEntry:`Walkway width carried into design: ${a} simulation m.`}); c.setDecisionFeedback(7,ok?'⭐ You copied the project requirement correctly.':'Your width is saved. It is different from the community brief, so it could create a problem later.');}}>Add width to my plan</button>{c.feedback[7]&&<p className="action-feedback">{c.feedback[7]}</p>}</article>

    <article className={task(8)}><div><span>🌧️ Look for flood clues</span><h3>Old photos, river marks and residents show that the water can rise about {s.floodRiseMetres} simulation m. What will you do with this clue?</h3></div><div className="choice-grid"><button type="button" onClick={()=>{c.setState(current=>({...current,floodIdentified:true})); c.recordAttempt(8,true,true,{completeOnAttempt:true,notebookSection:'ENVIRONMENTAL_INFORMATION',notebookEntry:`Seasonal flood evidence retained: ${s.floodRiseMetres} simulation m.`}); c.setDecisionFeedback(8,'🌧️ Flood clue saved in your notebook for later.');}}>Keep the flood clue in my plan</button><button type="button" onClick={()=>{c.setState(current=>({...current,floodIdentified:false})); c.recordAttempt(8,false,false,{completeOnAttempt:true,misconceptionTag:'ENVIRONMENTAL_REASONING_ERROR',notebookSection:'ENVIRONMENTAL_INFORMATION',notebookEntry:'Learner chose not to carry seasonal flood evidence into later planning.'}); c.setDecisionFeedback(8,'Your choice is saved. The adventure will not tell you yet whether this clue becomes important.');}}>Leave the flood clue out</button></div>{c.feedback[8]&&<p className="action-feedback">{c.feedback[8]}</p>}</article>

    <article className={task(9)}><div><span>🗺️ Make a mini plan</span><h3>Draw the crossing to scale on your planning board.</h3></div><div className="evidence-strip"><b>Your measured span:</b> {c.state.riverSpanStudent??'—'} simulation m <b>Scale:</b> 1 cm represents {s.scaleMetresPerCm} simulation m</div><textarea rows={2} value={c.working[9]??''} onChange={e=>c.setWorkingText(9,e.target.value)} placeholder="Use this space for your working..."/><input type="number" inputMode="decimal" value={c.response(9)} onChange={e=>c.setResponse(9,e.target.value)} placeholder="Drawing length in cm"/><div className="task-buttons"><button className="btn btn-primary" type="button" disabled={!c.state.riverSpanStudent} onClick={()=>{const a=Number(c.response(9)); if(!Number.isFinite(a)||c.response(9)==='')return c.setDecisionFeedback(9,'Enter the length your drawing should have.'); const span=c.state.riverSpanStudent??selectedSite?.spanMetres??0; const expected=span/s.scaleMetresPerCm; const ok=Math.abs(a-expected)<=.1; c.updateCalculatedQuantity('scaleDrawingCm',a); c.recordAttempt(9,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'SCALE_ERROR',notebookSection:'SCALE_DRAWING',notebookEntry:`Scale drawing submitted: ${a} cm at 1 cm : ${s.scaleMetresPerCm} simulation m.`}); c.setDecisionFeedback(9,ok?'⭐ Your mini plan matches the scale!':'Your scale plan is saved. A scale mistake affects your planning score, but it will not magically make the bridge fall down.');}}>Check my scale plan</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(9)}>💡 Give me a hint</button></div>{hint(9,['How many simulation metres does one centimetre stand for?','Use the span you measured yourself.','Drawing length = measured span ÷ metres represented by 1 cm.','Divide your measured span by the scale number shown above.'])&&<p className="hint-box">{hint(9,['How many simulation metres does one centimetre stand for?','Use the span you measured yourself.','Drawing length = measured span ÷ metres represented by 1 cm.','Divide your measured span by the scale number shown above.'])}</p>}{c.feedback[9]&&<p className="action-feedback">{c.feedback[9]}</p>}</article>

    {c.missionComplete(2)&&<button className="mission-advance" type="button" onClick={c.unlockNextMission}>🧩 River explored! Kojo says: “Great work — now let’s choose a bridge idea.” →</button>}
  </div>;
}
