import { distanceSavedMetres, journeyReductionPercent } from '../../footbridge/scenarioEngine';
import { FootbridgeController } from '../../footbridge/useFootbridgeProject';

export default function FootbridgeMission1({ c }: { c: FootbridgeController }) {
  const s = c.state.scenario;
  const expectedSaved = distanceSavedMetres(s);
  const expectedReduction = journeyReductionPercent(s);
  const distanceAttempts = c.recordFor(3).attempts;
  const latestDistanceAnswer = distanceAttempts.length ? distanceAttempts[distanceAttempts.length - 1].answer : undefined;
  const distanceAnswerLabel = typeof latestDistanceAnswer === 'number' ? `${latestDistanceAnswer} m` : 'not yet recorded';
  const task = (id: number) => c.recordFor(id).completed ? 'project-action complete' : 'project-action';
  const hint = (id: number, levels: string[]) => {
    const level = c.recordFor(id).highestHintLevel;
    return level ? levels[Math.min(level, levels.length) - 1] : '';
  };

  return <div className="project-mission-content">
    <div className="mission-narrative"><span>🏘️ MISSION 1 · MEET THE COMMUNITIES</span><h2>Why do Adom and Nkabom need your help?</h2><p>Ama has invited you to explore the problem. People on both sides of the river travel a long way to reach school, farms and the market. Find out what is happening before you decide what to build.</p></div>
    <div className="community-data-grid">
      <article><strong>👥 {s.dailyUsers}</strong><span>people use the route each day</span></article><article><strong>🎒 {s.schoolchildren}</strong><span>schoolchildren</span></article><article><strong>🌾 {s.farmers}</strong><span>farmers</span></article><article><strong>🧺 {s.traders}</strong><span>traders</span></article><article><strong>⏰ {s.peakUsers}</strong><span>people at the busiest moment</span></article>
    </div>

    <article className={task(1)}><div><span>🔎 Talk to the community</span><h3>What is the biggest problem the people want you to solve?</h3></div><div className="choice-grid">
      {[
        ['detour','The river makes people travel a much longer way between Adom and Nkabom.'],
        ['market','The communities mainly need a bigger market building.'],
        ['parking','The communities mainly need a new parking area.'],
      ].map(([value,label]) => <button key={value} type="button" onClick={() => { const correct=value==='detour'; c.recordAttempt(1,value,correct,{completeOnAttempt:true,misconceptionTag:correct?undefined:'DATA_INTERPRETATION_ERROR',notebookSection:'COMMUNITY_SURVEY',notebookEntry:`Community problem response: ${label}`}); c.setDecisionFeedback(1,correct?'⭐ Great detective work! You found the main problem.':'That choice is saved. Look again at what residents said about travelling between the two communities.'); }}>{label}</button>)}
    </div>{c.feedback[1]&&<p className="action-feedback">{c.feedback[1]}</p>}</article>

    <article className={task(2)}><div><span>👥 Read the people clues</span><h3>At the busiest time, how many people may need to use the crossing together?</h3></div><div className="calculation-clue-card"><div className="clue-card-heading"><span>📌 CLUES FOR THIS TASK</span><strong>Read the right number</strong></div><div className="fact-pill-grid"><span><b>{s.dailyUsers}</b> people during the whole day</span><span><b>{s.peakUsers}</b> people at the busiest moment</span></div><p>Kojo says: “We need the number who may be there <b>at the same time</b>, not everyone who travels during the whole day.”</p></div><input type="number" inputMode="numeric" value={c.response(2)} onChange={e=>c.setResponse(2,e.target.value)} placeholder="Type the busiest-time number"/><button className="btn btn-primary" type="button" onClick={()=>{const a=Number(c.response(2)); if(!Number.isFinite(a)||c.response(2)==='') return c.setDecisionFeedback(2,'Enter the busiest-time number first.'); const correct=a===s.peakUsers; c.recordAttempt(2,a,correct,{completeOnAttempt:true,misconceptionTag:correct?undefined:'DATA_INTERPRETATION_ERROR',notebookSection:'COMMUNITY_SURVEY',notebookEntry:`Peak-use figure recorded by learner: ${a}.`}); c.setDecisionFeedback(2,correct?'⭐ You spotted the correct peak-use number!':'Almost! Daily users and people there at the same time are different clues. Check the task facts.');}}>Save this clue</button>{c.feedback[2]&&<p className="action-feedback">{c.feedback[2]}</p>}</article>

    <article className={task(3)}><div><span>🛣️ How much shorter?</span><h3>If the new crossing is built, how many metres could a typical journey save?</h3></div><div className="calculation-clue-card travel-facts"><div className="clue-card-heading"><span>🗺️ TRAVEL FACTS</span><strong>Everything you need is here</strong></div><div className="fact-pill-grid three"><span><small>Current long route</small><b>{s.originalJourneyKm} km</b></span><span><small>Journey after connection</small><b>{s.newJourneyMetres} m</b></span><span><small>Unit clue</small><b>1 km = 1000 m</b></span></div><ol><li>Change the old journey from kilometres to metres.</li><li>Then subtract the new journey from the old journey.</li></ol><div className="formula-strip">Distance saved = old journey − new journey</div></div><textarea rows={3} value={c.working[3]??''} onChange={e=>c.setWorkingText(3,e.target.value)} placeholder={`Show your working here, e.g. ${s.originalJourneyKm} × 1000 = ...`}/><input type="number" inputMode="decimal" value={c.response(3)} onChange={e=>c.setResponse(3,e.target.value)} placeholder="Distance saved in metres"/><div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{const a=Number(c.response(3)); if(!Number.isFinite(a)||c.response(3)==='') return c.setDecisionFeedback(3,'Enter the distance you worked out.'); const correct=Math.abs(a-expectedSaved)<=1; c.recordAttempt(3,a,correct,{completeOnAttempt:true,misconceptionTag:correct?undefined:'UNIT_CONVERSION_ERROR',notebookSection:'CALCULATIONS',notebookEntry:`Learner distance-saving result: ${a} m.`}); c.setDecisionFeedback(3,correct?'⭐ Excellent! Your maths shows how much shorter the journey could be.':'Your answer is saved. Check the Travel Facts again: first make both distances metres, then subtract.');}}>Check my maths</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(3)}>💡 Give me a hint</button></div>{hint(3,['Are both journey distances using the same unit?','Try changing the old journey from kilometres into metres first.','Distance saved = old distance − new distance.','Multiply kilometres by 1000, then subtract the new journey in metres.'])&&<p className="hint-box">{hint(3,['Are both journey distances using the same unit?','Try changing the old journey from kilometres into metres first.','Distance saved = old distance − new distance.','Multiply kilometres by 1000, then subtract the new journey in metres.'])}</p>}{c.feedback[3]&&<p className="action-feedback">{c.feedback[3]}</p>}</article>

    <article className={task(4)}><div><span>📉 See the difference</span><h3>What percentage of the old journey could be removed?</h3></div><div className="calculation-clue-card travel-facts"><div className="clue-card-heading"><span>📊 USE YOUR TRAVEL RESULTS</span><strong>Turn the saving into a percentage</strong></div><div className="fact-pill-grid three"><span><small>Original journey</small><b>{s.originalJourneyKm} km</b></span><span><small>Your distance-saved answer</small><b>{distanceAnswerLabel}</b></span><span><small>Unit clue</small><b>1 km = 1000 m</b></span></div><p>If your distance-saved answer does not look right, use <b>Back</b> to revisit the previous session before calculating this percentage.</p><div className="formula-strip">Percentage reduction = distance saved ÷ original journey × 100</div></div><textarea rows={3} value={c.working[4]??''} onChange={e=>c.setWorkingText(4,e.target.value)} placeholder="Show your percentage working here..."/><input type="number" inputMode="decimal" value={c.response(4)} onChange={e=>c.setResponse(4,e.target.value)} placeholder="Percentage reduction"/><div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{const a=Number(c.response(4)); if(!Number.isFinite(a)||c.response(4)==='') return c.setDecisionFeedback(4,'Enter the percentage you worked out.'); const correct=Math.abs(a-expectedReduction)<=0.2; c.recordAttempt(4,a,correct,{completeOnAttempt:true,misconceptionTag:correct?undefined:'PERCENTAGE_ERROR',notebookSection:'CALCULATIONS',notebookEntry:`Learner journey-reduction result: ${a}%.`}); c.setDecisionFeedback(4,correct?'⭐ Brilliant! You can now show the community how big the change could be.':'Your answer is saved. Make sure the distance saved and original journey are in the same unit before dividing.');}}>Check my percentage</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(4)}>💡 Give me a hint</button></div>{hint(4,['What part of the original journey did you remove?','Use your distance saved and the original journey in the same unit.','Percentage reduction = distance saved ÷ original distance × 100.','Use the original journey in metres as the denominator.'])&&<p className="hint-box">{hint(4,['What part of the original journey did you remove?','Use your distance saved and the original journey in the same unit.','Percentage reduction = distance saved ÷ original distance × 100.','Use the original journey in metres as the denominator.'])}</p>}{c.feedback[4]&&<p className="action-feedback">{c.feedback[4]}</p>}</article>

    {c.missionComplete(1)&&<button className="mission-advance" type="button" onClick={c.unlockNextMission}>🌊 Mission complete! Ama says: “Great work — now let’s explore the river!” →</button>}
  </div>;
}
