import { FootbridgeController } from '../../footbridge/useFootbridgeProject';

function tolerance(level: number) { return level === 1 ? 0.2 : level === 3 ? 0.05 : 0.1; }

export default function FootbridgeMission2({ c }: { c: FootbridgeController }) {
  const s = c.state.scenario;
  const selectedSite = s.sites.find(site => site.id === c.state.selectedSiteId);
  const task = (id:number) => c.recordFor(id).completed ? 'project-action complete' : 'project-action';
  const scoreSite = (site: typeof s.sites[number]) => site.accessRating + site.environmentalRating + site.convenienceRating - site.spanMetres * .08 - site.costFactor;
  const bestSite = [...s.sites].sort((a,b)=>scoreSite(b)-scoreSite(a))[0];
  const hint = (id:number, levels:string[]) => { const level=c.recordFor(id).highestHintLevel; return level?levels[Math.min(level,levels.length)-1]:''; };

  return <div className="project-mission-content">
    <div className="mission-narrative"><span>Mission 2 · Field survey</span><h2>Survey the river before design work begins.</h2><p>Compare crossing locations, take your own measurement, retrieve the walkway requirement, investigate seasonal evidence and prepare a scale plan.</p></div>

    <article className={task(5)}><div><span>Crossing-location study</span><h3>Choose the site you believe gives the strongest overall balance, then justify the decision.</h3></div><div className="site-grid">{s.sites.map(site=><button key={site.id} type="button" className={c.state.selectedSiteId===site.id?'selected':''} onClick={()=>c.setState(current=>({...current,selectedSiteId:site.id}))}><strong>{site.name}</strong><span>{site.narrative}</span><small>Access {site.accessRating}/5 · Environment {site.environmentalRating}/5 · Convenience {site.convenienceRating}/5 · Relative cost {site.costFactor.toFixed(2)}</small></button>)}</div><textarea rows={3} value={c.response('5-reason')} onChange={e=>c.setResponse('5-reason',e.target.value)} placeholder="Why is this location appropriate? Consider access, environment, convenience and cost."/><button className="btn btn-primary" type="button" disabled={!selectedSite} onClick={()=>{if(!selectedSite)return; const reason=c.response('5-reason').trim(); if(reason.length<10)return c.setDecisionFeedback(5,'Add a short justification before submitting the site recommendation.'); const correct=selectedSite.id===bestSite.id; c.recordAttempt(5,selectedSite.id,correct,{completeOnAttempt:true,misconceptionTag:correct?undefined:'LOGICAL_REASONING_ERROR',notebookSection:'SITE_SURVEY',notebookEntry:`Crossing selected: ${selectedSite.name}. Learner justification: ${reason}`}); c.setDecisionFeedback(5,correct?'The committee rates this as the strongest overall balance in this scenario.':'The site choice is recorded. Another location scores more strongly across the supplied factors, but your project will continue with the site you selected.');}}>Submit site recommendation</button>{c.feedback[5]&&<p className="action-feedback">{c.feedback[5]}</p>}</article>

    <article className={task(6)}><div><span>Interactive measurement</span><h3>Measure the selected crossing and record the span you discovered.</h3></div>{!selectedSite?<p className="locked-note">Choose a crossing location first.</p>:<><div className="survey-tool"><span>Bank marker A</span><i/><span>Bank marker B</span><small>The actual span is hidden. In VR this reading will come from the measurement tool; this web control is the desktop/tablet fallback.</small></div><input type="number" inputMode="decimal" value={c.response(6)} onChange={e=>c.setResponse(6,e.target.value)} placeholder="Your measured span in simulation metres"/><div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{const a=Number(c.response(6)); if(!Number.isFinite(a)||a<=0||c.response(6)==='')return c.setDecisionFeedback(6,'Record a positive measurement before leaving the riverbank.'); const ok=Math.abs(a-selectedSite.spanMetres)<=tolerance(s.difficultyLevel); c.setState(current=>({...current,riverSpanStudent:a})); c.recordAttempt(6,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'MEASUREMENT_ERROR',notebookSection:'MEASUREMENTS',notebookEntry:`Learner river measurement: ${a} simulation m at ${selectedSite.name}.`}); c.setDecisionFeedback(6,ok?`Measurement is within the ±${tolerance(s.difficultyLevel)} m survey tolerance.`:'Measurement recorded. It is outside the normal survey tolerance and may affect later project quantities if you do not revise it.');}}>Record measurement</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(6)}>Hint</button></div>{hint(6,['Check that both ends of your measuring tool touch the bank markers.','Measure across the proposed crossing, not along the riverbank.','Record the span to one decimal place and compare your endpoints carefully.','Reset the tool between the two marked bank points and take a fresh reading.'])&&<p className="hint-box">{hint(6,['Check that both ends of your measuring tool touch the bank markers.','Measure across the proposed crossing, not along the riverbank.','Record the span to one decimal place and compare your endpoints carefully.','Reset the tool between the two marked bank points and take a fresh reading.'])}</p>}</>}{c.feedback[6]&&<p className="action-feedback">{c.feedback[6]}</p>}</article>

    <article className={task(7)}><div><span>Project brief</span><h3>The brief requires a walkway width of <b>{s.walkwayRequirementMetres} simulation m</b>. Transfer the width into your design record.</h3></div><input type="number" inputMode="decimal" value={c.response(7)} onChange={e=>c.setResponse(7,e.target.value)} placeholder="Walkway width"/><button className="btn btn-primary" type="button" onClick={()=>{const a=Number(c.response(7)); if(!Number.isFinite(a)||a<=0||c.response(7)==='')return c.setDecisionFeedback(7,'Enter the width you are carrying into the design.'); const ok=Math.abs(a-s.walkwayRequirementMetres)<.01; c.setState(current=>({...current,walkwaySelected:a})); c.recordAttempt(7,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'DATA_INTERPRETATION_ERROR',notebookSection:'MEASUREMENTS',notebookEntry:`Walkway width carried into design: ${a} simulation m.`}); c.setDecisionFeedback(7,ok?'The project requirement has been transferred accurately.':'Width recorded. It differs from the project brief and may create a usability issue later.');}}>Transfer width</button>{c.feedback[7]&&<p className="action-feedback">{c.feedback[7]}</p>}</article>

    <article className={task(8)}><div><span>Seasonal investigation</span><h3>Flood markers, resident testimony and historic images indicate a seasonal rise of about {s.floodRiseMetres} simulation m. What will you carry into the project record?</h3></div><div className="choice-grid"><button type="button" onClick={()=>{c.setState(current=>({...current,floodIdentified:true})); c.recordAttempt(8,true,true,{completeOnAttempt:true,notebookSection:'ENVIRONMENTAL_INFORMATION',notebookEntry:`Seasonal flood evidence retained: ${s.floodRiseMetres} simulation m.`}); c.setDecisionFeedback(8,'Environmental observation recorded for later project decisions.');}}>Record the seasonal flood evidence</button><button type="button" onClick={()=>{c.setState(current=>({...current,floodIdentified:false})); c.recordAttempt(8,false,false,{completeOnAttempt:true,misconceptionTag:'ENVIRONMENTAL_REASONING_ERROR',notebookSection:'ENVIRONMENTAL_INFORMATION',notebookEntry:'Learner chose not to carry seasonal flood evidence into later planning.'}); c.setDecisionFeedback(8,'Your environmental decision has been recorded. The simulation will not tell you yet whether it matters.');}}>Do not carry it forward</button></div>{c.feedback[8]&&<p className="action-feedback">{c.feedback[8]}</p>}</article>

    <article className={task(9)}><div><span>Virtual planning board</span><h3>Prepare a scale representation of your measured crossing.</h3></div><div className="evidence-strip"><b>Your recorded span:</b> {c.state.riverSpanStudent??'—'} simulation m <b>Scale:</b> 1 cm represents {s.scaleMetresPerCm} simulation m</div><textarea rows={2} value={c.working[9]??''} onChange={e=>c.setWorkingText(9,e.target.value)} placeholder="Working board"/><input type="number" inputMode="decimal" value={c.response(9)} onChange={e=>c.setResponse(9,e.target.value)} placeholder="Drawing length in cm"/><div className="task-buttons"><button className="btn btn-primary" type="button" disabled={!c.state.riverSpanStudent} onClick={()=>{const a=Number(c.response(9)); if(!Number.isFinite(a)||c.response(9)==='')return c.setDecisionFeedback(9,'Enter your scale drawing length.'); const span=c.state.riverSpanStudent??selectedSite?.spanMetres??0; const expected=span/s.scaleMetresPerCm; const ok=Math.abs(a-expected)<=.1; c.updateCalculatedQuantity('scaleDrawingCm',a); c.recordAttempt(9,a,ok,{completeOnAttempt:true,misconceptionTag:ok?undefined:'SCALE_ERROR',notebookSection:'SCALE_DRAWING',notebookEntry:`Scale drawing submitted: ${a} cm at 1 cm : ${s.scaleMetresPerCm} simulation m.`}); c.setDecisionFeedback(9,ok?'Scale plan is mathematically consistent with your recorded measurement.':'Scale plan recorded. A scale error lowers planning accuracy but does not automatically make the bridge fail.');}}>Submit scale plan</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(9)}>Hint</button></div>{hint(9,['How many simulation metres does one centimetre represent?','Use the span you measured, not a hidden ideal value.','Drawing length = recorded span ÷ metres represented by 1 cm.','Divide your measured span by the scale number shown on the planning board.'])&&<p className="hint-box">{hint(9,['How many simulation metres does one centimetre represent?','Use the span you measured, not a hidden ideal value.','Drawing length = recorded span ÷ metres represented by 1 cm.','Divide your measured span by the scale number shown on the planning board.'])}</p>}{c.feedback[9]&&<p className="action-feedback">{c.feedback[9]}</p>}</article>

    {c.missionComplete(2)&&<button className="mission-advance" type="button" onClick={c.unlockNextMission}>Your field survey is complete. Report to the planning office →</button>}
  </div>;
}
