import { distanceSavedMetres, journeyReductionPercent } from '../../footbridge/scenarioEngine';
import { FootbridgeController } from '../../footbridge/useFootbridgeProject';

export default function FootbridgeMission1({ c }: { c: FootbridgeController }) {
  const s = c.state.scenario;
  const expectedSaved = distanceSavedMetres(s);
  const expectedReduction = journeyReductionPercent(s);
  const task = (id: number) => c.recordFor(id).completed ? 'project-action complete' : 'project-action';
  const hint = (id: number, levels: string[]) => {
    const level = c.recordFor(id).highestHintLevel;
    return level ? levels[Math.min(level, levels.length) - 1] : '';
  };

  return <div className="project-mission-content">
    <div className="mission-narrative"><span>Mission 1 · Community briefing</span><h2>Understand the problem before proposing a solution.</h2><p>Adom and Nkabom are separated by a river. Residents currently travel a much longer route. Investigate who uses the route and what difference a direct connection could make.</p></div>
    <div className="community-data-grid">
      <article><strong>{s.dailyUsers}</strong><span>daily users</span></article><article><strong>{s.schoolchildren}</strong><span>schoolchildren</span></article><article><strong>{s.farmers}</strong><span>farmers</span></article><article><strong>{s.traders}</strong><span>traders</span></article><article><strong>{s.peakUsers}</strong><span>peak simultaneous users</span></article>
    </div>

    <article className={task(1)}><div><span>Community investigation</span><h3>Identify the main problem the project team has been asked to address.</h3></div><div className="choice-grid">
      {[
        ['detour','The river separation forces a much longer journey between Adom and Nkabom.'],
        ['market','The communities need a larger market hall.'],
        ['parking','The communities mainly need a vehicle parking area.'],
      ].map(([value,label]) => <button key={value} type="button" onClick={() => { const correct=value==='detour'; c.recordAttempt(1,value,correct,{completeOnAttempt:true,misconceptionTag:correct?undefined:'DATA_INTERPRETATION_ERROR',notebookSection:'COMMUNITY_SURVEY',notebookEntry:`Community problem response: ${label}`}); c.setDecisionFeedback(1,correct?'Your investigation identifies the central community problem.':'Your response is recorded. The project will continue, but the community evidence suggests a different central problem.'); }}>{label}</button>)}
    </div>{c.feedback[1]&&<p className="action-feedback">{c.feedback[1]}</p>}</article>

    <article className={task(2)}><div><span>Community-use information</span><h3>Record the number of people the project must consider at the busiest moment.</h3></div><input type="number" inputMode="numeric" value={c.response(2)} onChange={e=>c.setResponse(2,e.target.value)} placeholder="Peak simultaneous users"/><button className="btn btn-primary" type="button" onClick={()=>{const a=Number(c.response(2)); if(!Number.isFinite(a)||c.response(2)==='') return c.setDecisionFeedback(2,'Enter the peak-use figure before recording it.'); const correct=a===s.peakUsers; c.recordAttempt(2,a,correct,{completeOnAttempt:true,misconceptionTag:correct?undefined:'DATA_INTERPRETATION_ERROR',notebookSection:'COMMUNITY_SURVEY',notebookEntry:`Peak-use figure recorded by learner: ${a}.`}); c.setDecisionFeedback(2,correct?'Peak-use information interpreted correctly.':'Recorded. Daily users and peak simultaneous users are different measures; this will affect your competency report.');}}>Record community-use information</button>{c.feedback[2]&&<p className="action-feedback">{c.feedback[2]}</p>}</article>

    <article className={task(3)}><div><span>Journey analysis</span><h3>Calculate the distance saved by the new connection.</h3></div><div className="evidence-strip"><b>Existing route:</b> {s.originalJourneyKm} km <b>New route:</b> {s.newJourneyMetres} m</div><textarea rows={2} value={c.working[3]??''} onChange={e=>c.setWorkingText(3,e.target.value)} placeholder="Working board"/><input type="number" inputMode="decimal" value={c.response(3)} onChange={e=>c.setResponse(3,e.target.value)} placeholder="Distance saved in metres"/><div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{const a=Number(c.response(3)); if(!Number.isFinite(a)||c.response(3)==='') return c.setDecisionFeedback(3,'Enter your calculated distance saving.'); const correct=Math.abs(a-expectedSaved)<=1; c.recordAttempt(3,a,correct,{completeOnAttempt:true,misconceptionTag:correct?undefined:'UNIT_CONVERSION_ERROR',notebookSection:'CALCULATIONS',notebookEntry:`Learner distance-saving result: ${a} m.`}); c.setDecisionFeedback(3,correct?'Distance saving calculated correctly.':'Result recorded. Recheck whether both distances were in the same unit before subtraction.');}}>Record calculation</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(3)}>Hint</button></div>{hint(3,['Are both journey distances in the same unit?','Convert the existing journey from kilometres to metres first.','Distance saved = original distance − new distance.','Multiply kilometres by 1000, then subtract the new journey in metres.'])&&<p className="hint-box">{hint(3,['Are both journey distances in the same unit?','Convert the existing journey from kilometres to metres first.','Distance saved = original distance − new distance.','Multiply kilometres by 1000, then subtract the new journey in metres.'])}</p>}{c.feedback[3]&&<p className="action-feedback">{c.feedback[3]}</p>}</article>

    <article className={task(4)}><div><span>Community impact</span><h3>Calculate the percentage reduction in journey distance.</h3></div><textarea rows={2} value={c.working[4]??''} onChange={e=>c.setWorkingText(4,e.target.value)} placeholder="Working board"/><input type="number" inputMode="decimal" value={c.response(4)} onChange={e=>c.setResponse(4,e.target.value)} placeholder="Percentage reduction"/><div className="task-buttons"><button className="btn btn-primary" type="button" onClick={()=>{const a=Number(c.response(4)); if(!Number.isFinite(a)||c.response(4)==='') return c.setDecisionFeedback(4,'Enter your percentage result.'); const correct=Math.abs(a-expectedReduction)<=0.2; c.recordAttempt(4,a,correct,{completeOnAttempt:true,misconceptionTag:correct?undefined:'PERCENTAGE_ERROR',notebookSection:'CALCULATIONS',notebookEntry:`Learner journey-reduction result: ${a}%.`}); c.setDecisionFeedback(4,correct?'Percentage reduction calculated correctly.':'Result recorded. Review the relationship between distance saved and the original distance.');}}>Record impact calculation</button><button className="btn btn-ghost" type="button" onClick={()=>c.useHint(4)}>Hint</button></div>{hint(4,['What fraction of the original journey has been removed?','Use your distance saved and the original journey in matching units.','Percentage reduction = distance saved ÷ original distance × 100.','Use the original journey in metres as the denominator.'])&&<p className="hint-box">{hint(4,['What fraction of the original journey has been removed?','Use your distance saved and the original journey in matching units.','Percentage reduction = distance saved ÷ original distance × 100.','Use the original journey in metres as the denominator.'])}</p>}{c.feedback[4]&&<p className="action-feedback">{c.feedback[4]}</p>}</article>

    {c.missionComplete(1)&&<button className="mission-advance" type="button" onClick={c.unlockNextMission}>Your community investigation is complete. Report to the river survey team →</button>}
  </div>;
}
